Add in a fallback-nic option when unconfigured booting.

diff --git a/overlay/generic/lib/svc/method/net-physical b/overlay/generic/lib/svc/method/net-physical
--- a/overlay/generic/lib/svc/method/net-physical
+++ b/overlay/generic/lib/svc/method/net-physical
@@ -260,8 +260,28 @@ if smf_is_globalzone; then
             /usr/sbin/dladm create-bridge -l ${SYSINFO_NIC_admin} vmwarebr
         fi
     else
-        echo "ERROR: admin NIC not found, unable to bring up admin network."
-        exit ${SMF_EXIT_ERR_CONFIG}
+
+        # Hmm, no admin nic configured. Try to get a DHCP lease from the first available link...
+        # (We're probably in unconfigured boot)
+        fallback_nic=`dladm show-link -po link | head -1`
+
+        if [[ -n ${fallback_nic} ]]; then
+            echo "Using fallback nic ${fallback_nic} as no admin nic is configured."
+
+            # Plumb it and kick off DHCP
+            ifconfig ${fallback_nic} unplumb || /bin/true
+
+            ifconfig ${fallback_nic} plumb
+            ifconfig ${fallback_nic} dhcp || /bin/true
+
+            # Setup a "hope for the best" DNS configuration
+            echo "nameserver 8.8.8.8" >  /etc/resolv.conf
+            echo "nameserver 8.8.4.4" >> /etc/resolv.conf
+
+        else
+            echo "ERROR: admin NIC not found, and couldn't find any links to bring up."
+            exit ${SMF_EXIT_ERR_CONFIG}
+        fi
     fi
 
     # Setup external NIC
